### ISSUE TITLE
Can't find "pdclib/_PDCLIB_config.h"

### ISSUE THREAD

**Issue by ZhouJiatai** [DevSolar/pdclib#15]
I create a C source in this repo "\include" folder and compile it:
```
#include ".\stdio.h"
int main()
{
    printf("Hello, PDCLib!");
    return 0;
}
```
And Compiler (MinGW-w64) says,
> E:\source\repos\pdclib\include\pdclib\_PDCLIB_int.h|19|fatal error: pdclib/_PDCLIB_config.h: No such file or directory|

I see "_PDCLIB_int.h", in Line 19:
`#include "pdclib/_PDCLIB_config.h"`
I can't find "pdclib/_PDCLIB_config.h" in this repo. Where is "pdclib/_PDCLIB_config.h"?

**Comment by DevSolar** [comment]
This is not how PDCLib is supposed to be used. Please refer to Quickstart.txt.
