### ISSUE TITLE
Set repository URL on GitHub

### ISSUE THREAD

**Issue by JayFoxRox** [DevSolar/pdclib#6]
https://rootdirectory.ddns.net/dokuwiki/doku.php?id=pdclib:start should be made the repository URL (next to article description) of the GitHub repo as it's an informative resource, that's currently hidden.

**Comment by DevSolar** [comment]
Actually http://pdclib.rootdirectory.de is the "entry URL". I created the GitHub project for the sole purpose of providing a Git "mirror" of the SVN repository, as that was requested by some; I never figured that people would "enter" into PDCLib from GitHub, and actually don't "do" anything via GitHub, so I never did spend much thought on GitHub configuration. Thanks for the heads-up.

**Comment by dracc** [comment]
I hate to be that guy but https://pdclib.rootdirectory.de currently gives a certificate warning.

**Comment by DevSolar** [comment]
Can't be helped for now. Rootdirectory.de is a domain registered to my name, and which is (with a webhosting service) configured to forward to the fileserver in my basement (which is DDNS'd to rootdirectory.ddns.net). Unfortunately the domain forwarding / rewrite doesn't play together with SSL.
