### ISSUE TITLE
Move "Status" section out of "Get the Source" wiki article

### ISSUE THREAD

**Issue by JayFoxRox** [DevSolar/pdclib#7]
https://rootdirectory.ddns.net/dokuwiki/doku.php?id=pdclib:source#status should be moved to either of those:

- The https://rootdirectory.ddns.net/dokuwiki/doku.php?id=pdclib:start article 
- A separate, more prominent article

The implementation status is not really related to "Get the Source" - it is "What is PDCLib" (which is what pdclib:start should be).

---

Minor related issues:

- The "Get the Source" link also shouldn't be in the "Status" section of pdclib:start, and be more prominent elsewhere in that article.
- The GitHub "Wiki" (along with "Projects") should be disabled in the GitHub settings: Those navigation links are dead for non-owners and mislead users into thinking the main wiki is on GitHub.

**Comment by DevSolar** [comment]
Done.
